
/// **Simple Itinerary Models - Hive Compatible**
/// 
/// Matches the exact JSON structure required by assignment (Spec A):
/// {
///   "title": "Kyoto 5-Day Solo Trip",
///   "startDate": "2025-04-10", 
///   "endDate": "2025-04-15",
///   "days": [...]
/// }
library;

/// Main itinerary model
class ItineraryModel {
  /// Unique identifier for the itinerary
  String id;
  
  /// Trip title generated by AI
  String title;
  
  /// Start date in ISO format (YYYY-MM-DD)
  String startDate;
  
  /// End date in ISO format (YYYY-MM-DD)  
  String endDate;
  
  /// List of daily plans
  List<DayPlanModel> days;
  
  /// User's original prompt that generated this itinerary
  String? originalPrompt;
  
  /// Timestamp when itinerary was created
  DateTime? createdAt;
  
  /// Timestamp when itinerary was last modified
  DateTime? updatedAt;

  ItineraryModel({
    required this.id,
    required this.title,
    required this.startDate,
    required this.endDate,
    required this.days,
    this.originalPrompt,
    this.createdAt,
    this.updatedAt,
  });

  /// Manual JSON serialization - simple and clean
  Map<String, dynamic> toJson() {
    return {
      'title': title,
      'startDate': startDate,
      'endDate': endDate,
      'days': days.map((day) => day.toJson()).toList(),
    };
  }

  /// Manual JSON deserialization
  factory ItineraryModel.fromJson(Map<String, dynamic> json) {
    // Parse days from JSON
    final daysData = json['days'] as List<dynamic>;
    final daysList = daysData.map((dayJson) => 
        DayPlanModel.fromJson(dayJson as Map<String, dynamic>)
    ).toList();
    
    return ItineraryModel(
      id: DateTime.now().millisecondsSinceEpoch.toString(),
      title: json['title'] as String,
      startDate: json['startDate'] as String,
      endDate: json['endDate'] as String,
      days: daysList,
      createdAt: DateTime.now(),
    );
  }
  
  /// Calculate trip duration in days
  int get durationDays => days.length;
}

/// Simple day plan model
class DayPlanModel {
  /// Date in ISO format (YYYY-MM-DD)
  String date;
  
  /// Brief summary of the day's theme
  String summary;
  
  /// List of activities/items for this day
  List<ActivityItemModel> items;

  DayPlanModel({
    required this.date,
    required this.summary,
    required this.items,
  });

  /// Manual serialization
  Map<String, dynamic> toJson() {
    return {
      'date': date,
      'summary': summary,
      'items': items.map((item) => item.toJson()).toList(),
    };
  }

  factory DayPlanModel.fromJson(Map<String, dynamic> json) {
    final itemsData = json['items'] as List<dynamic>;
    final itemsList = itemsData.map((itemJson) => 
        ActivityItemModel.fromJson(itemJson as Map<String, dynamic>)
    ).toList();
    
    return DayPlanModel(
      date: json['date'] as String,
      summary: json['summary'] as String,
      items: itemsList,
    );
  }
}

/// Activity item model
class ActivityItemModel {
  /// Time in HH:MM format (24-hour)
  String time;
  
  /// Activity description
  String activity;
  
  /// Location in "lat,lng" format for maps integration
  String location;

  ActivityItemModel({
    required this.time,
    required this.activity,
    required this.location,
  });

  /// Manual serialization
  Map<String, dynamic> toJson() {
    return {
      'time': time,
      'activity': activity,
      'location': location,
    };
  }

  /// Manual deserialization
  factory ActivityItemModel.fromJson(Map<String, dynamic> json) {
    return ActivityItemModel(
      time: json['time'] as String,
      activity: json['activity'] as String,
      location: json['location'] as String,
    );
  }
  
  /// Parse latitude from location string
  double? get latitude {
    try {
      final parts = location.split(',');
      return double.parse(parts[0]);
    } catch (e) {
      return null;
    }
  }
  
  /// Parse longitude from location string  
  double? get longitude {
    try {
      final parts = location.split(',');
      return double.parse(parts[1]);
    } catch (e) {
      return null;
    }
  }
  
  /// Get formatted time for display (12-hour format)
  String get formattedTime {
    try {
      final parts = time.split(':');
      final hour = int.parse(parts[0]);
      final minute = parts[1];
      
      if (hour == 0) return '12:$minute AM';
      if (hour < 12) return '$hour:$minute AM';
      if (hour == 12) return '12:$minute PM';
      return '${hour - 12}:$minute PM';
    } catch (e) {
      return time;
    }
  }
}

/// Chat message model
class ChatMessageModel {
  String id;
  String itineraryId;
  String content;
  String role; // 'user' or 'assistant'
  DateTime timestamp;
  
  /// Token usage for this message (cost tracking)
  int? tokenCount;

  ChatMessageModel({
    required this.id,
    required this.itineraryId,
    required this.content,
    required this.role,
    required this.timestamp,
    this.tokenCount,
  });

  /// Simple JSON conversion
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'itineraryId': itineraryId,
      'content': content,
      'role': role,
      'timestamp': timestamp.toIso8601String(),
      'tokenCount': tokenCount,
    };
  }

  factory ChatMessageModel.fromJson(Map<String, dynamic> json) {
    return ChatMessageModel(
      id: json['id'] as String,
      itineraryId: json['itineraryId'] as String,
      content: json['content'] as String,
      role: json['role'] as String,
      timestamp: DateTime.parse(json['timestamp'] as String),
      tokenCount: json['tokenCount'] as int?,
    );
  }
}
